name: Run Crawler Daily

on:
  schedule:
    - cron: '0 14 * * *'  # Schedules to run daily at midnight AEST
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set timezone to AEST
        run: |
          sudo timedatectl set-timezone Australia/Sydney

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          UNIMELB_EMAIL: ${{ secrets.UNIMELB_EMAIL }}
          UNIMELB_PASSWORD: ${{ secrets.UNIMELB_PASSWORD }}
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        run: |
          python main.py 
