name: Run Crawler Daily

on:
  schedule:
    - cron: '0 23 * * *'  # 9 AM AEST
    - cron: '0 0 * * *'   # 10 AM AEST
    - cron: '0 1 * * *'   # 11 AM AEST
    - cron: '0 2 * * *'   # 12 PM AEST
    - cron: '0 3 * * *'   # 1 PM AEST
    - cron: '0 4 * * *'   # 2 PM AEST
    - cron: '0 5 * * *'   # 3 PM AEST
    - cron: '0 6 * * *'   # 4 PM AEST
    - cron: '0 7 * * *'   # 5 PM AEST
    - cron: '0 8 * * *'   # 6 PM AEST
  workflow_dispatch:  # Allows manual triggering of the workflow from GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set timezone to AEST
        run: |
          sudo timedatectl set-timezone Australia/Sydney

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        env:
          GMAIL_APP_PASSWORD: ${{ secrets.GMAIL_APP_PASSWORD }}
          GMAIL_EMAIL: ${{ secrets.GMAIL_EMAIL }}
        run: |
          python src/main.py 
